import type { Editor, JSONContent } from '@tiptap/core'
import type { MarkdownManager } from '@tiptap/markdown'
import { stripUnknownNodes, wrapBareInlineContent } from './MarkdownEditorMarkdownUtil'

export function getMarkdownManager(instance: Editor): MarkdownManager | null {
  return instance.markdown ?? instance.storage?.markdown?.manager ?? null;
}
function protectMathHtmlTags(text: string): { protected: string; restore: (s: string) => string } {
  const tags: string[] = [];
  const PROTECTED = '\x00MPH';
  let idx = 0;
  // Match both inline (<span data-type="inline-math"...) and block (<div data-type="block-math"...)
  const pattern = /<(span|div)\s+data-type="(?:inline|block)-math"[^>]*><\/(span|div)>/gi;
  const processed = text.replace(pattern, (match) => {
    const placeholder = `${PROTECTED}${idx}\x00`;
    tags.push(match);
    idx++;
    return placeholder;
  });
  return {
    protected: processed,
    restore: (s: string) => s.replace(/\x00MPH(\d+)\x00/g, (_m, i) => tags[parseInt(i)] ?? ''),
  };
}

/**
 * Escape all < as &lt; so marked doesn't treat text-in-angle-brackets as HTML tags.
 * Without this, content like <中文> or <**bold** text> creates invalid nodes.
 * Math HTML tags (generated by protectMathDollarSyntax) are protected from escaping.
 */
function escapeNonHtmlAngleBrackets(text: string): string {
  const { protected: processed, restore } = protectMathHtmlTags(text);
  return restore(processed.replace(/</g, '&lt;'));
}
function repairEmptyHeadings(json: JSONContent, mgr: MarkdownManager, rawContent: string): void {
  if (!json.content || json.type !== 'doc') return;

  // Index headings in the raw content by extracting heading lines
  const rawHeadings: { level: number; text: string }[] = [];
  const headingRe = /^(#{1,6})\s+(.+)$/gm;
  let m: RegExpExecArray | null;
  while ((m = headingRe.exec(rawContent)) !== null) {
    rawHeadings.push({ level: (m[1] ?? '').length, text: (m[2] ?? '').trim() });
  }

  let headingIdx = 0;
  for (const node of json.content) {
    if (node.type !== 'heading') continue;
    const h = node as JSONContent & { attrs?: { level?: number }; content?: JSONContent[] };

    // Only repair truly empty headings (content is [] or missing)
    if (h.content && h.content.length > 0) {
      headingIdx++;
      continue;
    }

    // Find the corresponding raw heading text
    const rawH = rawHeadings[headingIdx];
    if (rawH && rawH.level === (h.attrs?.level ?? 1)) {
      // Re-parse this heading in isolation to get proper inline content
      const prefix = '#'.repeat(rawH.level);
      try {
        const reparsed = mgr.parse(`${prefix} ${rawH.text}`);
        const reparsedHeading = reparsed.content?.find(n => n.type === 'heading');
        if (reparsedHeading?.content) {
          h.content = reparsedHeading.content;
        }
      } catch {
        console.error('[MarkdownEditor] heading reparse failed for:', rawH.text);
        // Fallback: plain text node
        h.content = [{ type: 'text', text: rawH.text }];
      }
    }
    headingIdx++;
  }
}

export function parseMarkdownContent(instance: Editor, content: string): JSONContent | null {
  const mgr = getMarkdownManager(instance);
  if (!mgr) return null;
  try {
    // Strip control characters that would break HTML/XML parsing
    content = sanitizeControlChars(content);
    // Convert ALL $$...$$ to $...$ to prevent blockMath-in-listItem errors.
    // ProseMirror schema forbids blockMath as a child of listItem, and the
    // block-math tokenizer produces blockMath nodes that fail validation inside
    // list items. The AI is told to use $...$ for all math, so $$ usage is rare.
    content = content.replace(/\$\$([\s\S]+?)\$\$/g, (_full, latex: string) => {
      return `$${latex.trim()}$`;
    });
    // Protect $...$ / $$...$$ math syntax from angle-bracket escaping so
    // that < inside LaTeX (e.g. $x < y$) is preserved. The custom
    // markdownTokenizer on the Mathematics extension handles these directly.
    const mathProtected = protectMathDollarSyntax(content);
    // Escape unprotected < to &lt; so marked doesn't treat text like <中文> as HTML.
    // Math HTML tags (from old saved content) are also protected from escaping.
    const htmlSafe = escapeNonHtmlAngleBrackets(mathProtected.protected);
    // Restore $...$ / $$...$$ math syntax so the custom tokenizer can parse it
    const finalContent = mathProtected.restore(htmlSafe);
    // Table tokens are handled by TableMarkdownParser (custom extension registered
    // on the editor). marked's gfm:true produces 'table' tokens; the extension
    // converts them directly to TipTap JSON without going through generateJSON.
    const parsed = mgr.parse(finalContent);

    // Strip nodes with unknown types, then wrap bare inline nodes in paragraphs
    const stripped = stripUnknownNodes(parsed, instance.schema) ?? parsed;
    const sanitized = wrapBareInlineContent(stripped);

    // Workaround for @tiptap/markdown bug: ordered lists corrupt parser state,
    // making all subsequent heading content empty. Repair by re-parsing each
    // empty heading's text from the original markdown content.
    repairEmptyHeadings(sanitized, mgr, content);

    instance.schema.nodeFromJSON(sanitized).check();
    return sanitized;
  } catch (err) {
    console.error('[MarkdownEditor] parseMarkdownContent failed:', err, 'content preview:', content.slice(0, 200));
    return null;
  }
}
function protectMathDollarSyntax(text: string): { protected: string; restore: (s: string) => string } {
  const blocks: string[] = [];
  const PROTECTED = '\x00MDS';
  let idx = 0;

  let processed = text;
  // Block math first ($$...$$) — multiline, non-greedy
  processed = processed.replace(/\$\$([\s\S]+?)\$\$/g, (match) => {
    const placeholder = `${PROTECTED}${idx}\x00`;
    blocks.push(match);
    idx++;
    return placeholder;
  });

  // Inline math ($...$) — single-line, exclude currency with (?![ \d])
  processed = processed.replace(/\$(?![ \d])([^$\n]+?)\$/g, (match) => {
    const placeholder = `${PROTECTED}${idx}\x00`;
    blocks.push(match);
    idx++;
    return placeholder;
  });

  return {
    protected: processed,
    restore: (s: string) => s.replace(/\x00MDS(\d+)\x00/g, (_m, i) => blocks[parseInt(i)] ?? ''),
  };
}

/**
 * Strip control characters that are invalid in HTML/XML and will break
 * the DOM parser used by generateJSON inside the markdown manager.
 */
function sanitizeControlChars(text: string): string {
  // Strip C1 control characters (U+0080-U+009F) — invalid in HTML/XML
  return text.replace(/[\x80-\x9f]/g, ' ');
}
export function parseMarkdownDoc(instance: Editor, content: string): JSONContent | null {
  return parseMarkdownContent(instance, content);
}
